[project]
name = "rock-paper-scissors"
description = "Rock-Paper-Scissors (commit-reveal) with leaderboard"
version = "0.2.0"
authors = ["Hammed Yakub"]

[contracts.rock-paper-scissors]
path = "contracts/rock-paper-scissors.clar"

[contracts.leaderboard]
path = "contracts/leaderboard.clar"
